### ISSUE TITLE
[Request] Adapt Colloid Icon Theme to Plasma 6 

### ISSUE THREAD

**Issue by higorslva** [vinceliuice/Colloid-icon-theme#100]
With the Plasma 6, some icons are missing on system (especially the symbolics ones). I've tried to adapt some, but only the notification that I have success.

![Screenshot_20240323_184622](https://github.com/vinceliuice/Colloid-icon-theme/assets/48228780/849f1dd5-9cc0-40a2-bdf9-33da6453aa98)

**Comment by vinceliuice** [comment]
Fixed now
