### ISSUE TITLE
[bug] Colloid Dark - dark mode inconsistencies with Plasma 6

### ISSUE THREAD

**Issue by EmptyVisual** [vinceliuice/Colloid-icon-theme#112]
**Describe the bug**
Colloid Dark - dark mode inconsistencies with Plasma 6

**To Reproduce**
1. Install Colloid from git master
2. Apply 'Colloid Dark' icon theme in KDE System Settings
3. Observe certain tray icons and application launcher icon is not utilising a dark mode variant.

**Screenshots**
Tray icons
![image](https://github.com/vinceliuice/Colloid-icon-theme/assets/4710051/c37ecd56-9009-44e6-a877-30b6c7826364)

Application Launcher Icon
![image](https://github.com/vinceliuice/Colloid-icon-theme/assets/4710051/7dfeabd5-152d-4a43-bba3-92983330cf04)

**Desktop (please complete the following information):**
 - OS: Arch
 - App KDE Plasma
 - Version 6.0.5

**Comment by HarshNarayanJha** [comment]
For me though (KDE Plasma 6, Arch, Garuda Linux), Display configuration icon is alright in dark mode, but the media `paused` icons and `Vaults` icons are not present

![image](https://github.com/vinceliuice/Colloid-icon-theme/assets/50262541/62ef482e-92a0-4b60-bdde-75c3945994f4)

Playing icon is fine
![image](https://github.com/vinceliuice/Colloid-icon-theme/assets/50262541/7d1e38c1-88df-451f-8343-1683d3fd03f2)

Over the blue, one is media paused, and the other is Plasma Vaults. How do you have the plasma vaults icon?
