### ISSUE TITLE
[request] KDE - no tint flag?

### ISSUE THREAD

**Issue by EmptyVisual** [vinceliuice/Colloid-icon-theme#113]
The FollowsColorScheme setting is typically enabled by default, but this can cause the default blue icons to appear less appealing when using various KDE color schemes. 

Would it be feasible to make FollowsColorScheme an optional flag rather than enabled by default? Alternatively, if we prefer to keep it enabled by default, could we incorporate a tweak into the installation script, such as `--tweaks notint` ?

Example
Default Blue with `FollowsColorScheme=false`
![image](https://github.com/vinceliuice/Colloid-icon-theme/assets/4710051/222ed5d9-40f7-4398-87cc-c42cf4c183c8)

Default Blue with `FollowsColorScheme=true` and using the Colloid-dark Color Theme (System Prefs > Colors & Themes > Colors > Accent Color From Color Scheme)
![image](https://github.com/vinceliuice/Colloid-icon-theme/assets/4710051/eebb6c79-e8b4-4efe-9fa8-b3614947dddc)

**Comment by vinceliuice** [comment]
No problem!
