### ISSUE TITLE
[Icon request] [RustDesk]

### ISSUE THREAD

**Issue by 24d1ed** [vinceliuice/Colloid-icon-theme#127]
**Tell me things about the app or icon**
1. App name: RustDesk
2. App Webside: or App Github Homepage: https://rustdesk.com/
3. App icon name: com.rustdesk.RustDesk, rustdesk

**Additional context**
3) Just rustdesk.svg does not work for rustdesk installed with flatpak for me.

**Comment by Burhanverse** [comment]
I have made a PR with the fixes just wait for the dev to merge it
