### ISSUE TITLE
svg user icons won't show, and instead it shows blank default icon (winapps)

### ISSUE THREAD

**Issue by DaRandomCube** [vinceliuice/Colloid-icon-theme#151]
**Describe the bug**
i have winapps installed and ofc windows apps will be on the menu, however their icons won't show despite even using their svg icons

**To Reproduce**
1. have winapps installed and apps are on the menu
2. see that the icons aren't showing
3. use their svg icons
4. it doesn't work

**Expected behavior**
atleast the svg app icon shows

**Screenshots**
![image](https://github.com/user-attachments/assets/d6ffb438-1e89-44b4-8e51-ad2499fef53f)

**Desktop (please complete the following information):**
 - OS: fedora
 - Version kde 6.2.2, fedora 41

**Additional context**
it only happens in qogir and colloid icons, but not other icon packs

**Comment by vinceliuice** [comment]
open those .desktop files and tell me icon name id

**Comment by DaRandomCube** [comment]
![image](https://github.com/user-attachments/assets/e892efa5-10ec-4576-8d43-8fd84aef2d2d)
the icon value is the svg, idk if that's the id

**Comment by DaRandomCube** [comment]
now they're fixed
thx
