### ISSUE TITLE
Dark theme is monochromatic

### ISSUE THREAD

**Issue by ljmill** [vinceliuice/Colloid-icon-theme#18]
Installation produces sets of icons: `colloid-*`, `colloid-*-dark`, and `colloid-*-light` (not sure what the purpose of the first one is, seems redundant?)

`Colloid-*-light` appears correct (results in colored icons and dark icons on panel). However, `colloid-*-dark ` results in monochromatic icons (see image below):

![icons](https://user-images.githubusercontent.com/97128740/177622230-30d61863-0556-47c6-b409-3cf197bd35ae.png)

Installed with `./install.sh -t red` as well as with other colors.

**Comment by vinceliuice** [comment]
Try reinstall it

**Comment by ljmill** [comment]
I installed it multiple times with multiple different parameters, including `./install.sh -s nord -t teal` as shown in the README. Each time the dark theme is monochromatic.

**Comment by cyl3x** [comment]
Have the same problem, but manually copy the Colloid-Light folder and execute the "sed -i 's/#363636/#dedede/g'" commands from the install script works

**Comment by juandejesuss** [comment]
First of all, thanks for the amazing theme, I love it =)

I have the same problem, tried re-installing and the problem persists, could you please help us fixing the issue from the origin, thanks in advance

**Comment by lookto** [comment]
I love these icons but have the same problem with colloid-nord and colloid-nord-dark. Freshly cloned and installed from this repo. colloid-nord-light works without problems.

**Comment by juandejesuss** [comment]
Now it works perfect, thanks for fixing the icon theme!!!
