### ISSUE TITLE
Request Scrcpy, Ex Falso & Quod Libet Icons

### ISSUE THREAD

**Issue by Anifyuli** [vinceliuice/Colloid-icon-theme#28]
Hello, Mister.
I have a suggestion to update this icons and add Scrcpy, Ex Falso and Quod Libet icons too in your next updates. Thanks for your excellent work

**Comment by kodemeister** [comment]
I second that. It would be awesome to have proper Ex Falso and Quod Libet icons. By default they are circular and don't match the rest of icons.
