### ISSUE TITLE
Lack of contrast on progress control buttons

### ISSUE THREAD

**Issue by Nakamerica** [vinceliuice/Colloid-icon-theme#32]
Hi, 

On a particular application (although I suspect this is application agnostic): Transmission, the resume and pause buttons have relatively low contrast compared to the default icon pack (adwaita). For reference: 

![Screenshot from 2022-10-25 23-55-50](https://user-images.githubusercontent.com/88226614/197853435-77a3a566-6149-47a8-b613-35ad3dd81356.png) (with the adwaita icon pack) 

![Screenshot from 2022-10-25 23-55-38](https://user-images.githubusercontent.com/88226614/197854672-abebe9b7-ea5f-4e12-944f-107949d814e4.png) (with the colloid icons pack) 

Not a huge deal, but it would add more polish to the pack, thanks.

**Comment by vinceliuice** [comment]
You can use the dark version

**Comment by Nakamerica** [comment]
Yeah you're right, that didn't cross my mind, thanks.
