### ISSUE TITLE
[Icon request] Rust Rover Jetbrains IDE

### ISSUE THREAD

**Issue by kszinhu** [vinceliuice/Colloid-icon-theme#68]
**Tell me things about the app or icon**
1. App name: Rust Rover
2. App Webside: https://www.jetbrains.com/pt-br/rust/
3. App icon name: com.jetbrains.RustRover

**Additional context**

### Original Icon

![image](https://github.com/vinceliuice/Colloid-icon-theme/assets/66069923/ddfb4ba3-e4a9-42ce-ae80-388b8fd8dd13)

### Another `Jetbrains` packages

![image](https://github.com/vinceliuice/Colloid-icon-theme/assets/66069923/24d48f37-2295-43ee-b830-1b66dc30a59d)

**Comment by vinceliuice** [comment]
added
