### ISSUE TITLE
[Icon request] Loupe

### ISSUE THREAD

**Issue by nikkar124** [vinceliuice/Colloid-icon-theme#77]
**Tell me things about the app or icon**
1. App name: Image viewer or Loupe
2. App Webside: https://gitlab.gnome.org/GNOME/loupe
3. Icon=`org.gnome.Loupe`

**Additional context**
Gnome 45 standard image viewer
Default icon: https://gitlab.gnome.org/GNOME/loupe/-/blob/main/data/icons/hicolor/scalable/apps/org.gnome.Loupe.svg

**Comment by vinceliuice** [comment]
added
