### ISSUE TITLE
[Icon Request] MATLAB

### ISSUE THREAD

**Issue by MrPancakes39** [vinceliuice/Colloid-icon-theme#89]
**Tell me things about the app or icon**
1. App name: MATLAB
2. App Webside: [MathWorks MATLAB](https://www.mathworks.com/products/matlab.html)
3. App icon name:
    - matlab
    - matlab-desktop

**Additional context**
MATLAB is a programming language and numeric computing environment developed by MathWorks.

**Comment by joezhouchenye** [comment]
![matlab](https://github.com/vinceliuice/Colloid-icon-theme/assets/59191277/5297039e-e20f-45ab-b269-332c05e4515d)

Use Inkscape and the template. It's very easy to customize your icon.

Just put it into the theme (name it as matlab.svg) and update the Icon field of your matlab's desktop file to `Icon=matlab`
