### ISSUE TITLE
[Icon request] GTKWave

### ISSUE THREAD

**Issue by YSqQrH0zurvGmYfF** [vinceliuice/Colloid-icon-theme#91]
1. App name: GTKWave
2. App Webside: https://gtkwave.sourceforge.net/
3. App icon name: `Icon=gtkwave`

**Additional context**
Waveform and multi-platform timing display software.
![image](https://github.com/vinceliuice/Colloid-icon-theme/assets/104148785/6a6c5acb-ec3e-436a-806a-765b393aea79)

**Comment by cobbdzon** [comment]
Made the icon for GTKWave. Just have to wait for it to get merged.
https://github.com/vinceliuice/Colloid-icon-theme/pull/98#issuecomment-1980043732

**Comment by cobbdzon** [comment]
Since #98 has been merged, you can close this issue now
